Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/06/202
  
Var
// Seção de Declarações das variáveis 

      //din:real
      // ano,nasc,idade:inteiro
      n:inteiro
      
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

       
       //se(din>=10000){
       //escreva("Partiu ferias")
       //}senao{
       //escreva("TRabalhe mais")
       //}
       
      //escreva("Em que ano estamos? ")
      //leia(ano)
      //escreva("Em que ano voce nasceu? ")
      //leia(nasc)
      //idade<-ano-nasc
      //escreva("Em",ano," voce tera",idade)
      //se(idade>=21)entao
      //Escreva(" e tera atingido a maior idade")
      //fimse
       
       //escreva("Escreva o seu valor monetario: ")
       //leia(din)
       
       //se(din>=10000)entao
       //escreva("Partil Disnei")
       //senao entao
       //escreva("Vai trebalhar")
       //fimse
       
       escreva("Escreva um numero qualquer: ")
       leia(n)
       se(n%2=0)entao
       escreva("O numero ",n," e Par")
       senao
       escreva("O numero ",n," e Impar")
       fimse
       

Fimalgoritmo